public class Main {
    public static void main(String[] args) {
        int line,column, toLine, toColumn;
        ChessBoard board = new ChessBoard("White");
        Horse horse = new Horse("White");

        line=3; column=3; toLine=5; toColumn=2;
        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=10; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=9; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=8; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=7; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=6; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=5; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=4; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=3; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=2; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=1; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=0; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-1; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-2; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-3; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=-3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=-2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=-1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=0;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=1;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=2;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=3;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=4;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=5;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=6;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=7;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));
//        line=3; column=3; toLine=-4; toColumn=8;
//        System.out.println("line"+line+"; column:"+column+"; toLine:"+toLine+"; toColumn:"+toColumn+"; canMove:"+horse.canMoveToPosition(board,line,column,toLine,toColumn));

    }
}
